# Generated by Django 6.1 on 2026-08-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Meu Site de Ofertas', max_length=100)),
                ('default_description', models.CharField(blank=True, max_length=160)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('google_analytics_id', models.CharField(blank=True, max_length=30)),
                ('google_search_console_verification', models.CharField(blank=True, max_length=100)),
                ('amazon_tracking_id', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
