# Generated by Django 6.1 on 2026-08-27 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('shopee', 'Shopee'), ('mercado_livre', 'Mercado Livre'), ('amazon', 'Amazon'), ('magalu', 'Magazine Luiza')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='platforms/')),
                ('highlight_color', models.CharField(default='#000000', max_length=7)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
            },
        ),
        migrations.CreateModel(
            name='AffiliateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(help_text='SKU/ASIN/item ID on the platform', max_length=100)),
                ('affiliate_url', models.URLField(help_text='Link already containing your affiliate code', max_length=1000)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_error', models.CharField(blank=True, max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='products.product')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='affiliates.platform')),
            ],
        ),
        migrations.CreateModel(
            name='ClickLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, help_text='Referrer: blog post, category, search...', max_length=255)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_logs', to='affiliates.affiliatelink')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['link', 'created_at'], name='affiliates__link_id_2cfa2f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='affiliatelink',
            index=models.Index(fields=['product', 'platform'], name='affiliates__product_abf515_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='affiliatelink',
            unique_together={('platform', 'external_id')},
        ),
    ]
