# Generated by Django 6.1 on 2026-08-27 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliates', '0001_initial'),
        ('products', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('running', 'Em execução'), ('success', 'Sucesso'), ('failed', 'Falhou'), ('partial', 'Parcial')], default='running', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('total_products', models.IntegerField(default=0)),
                ('updated_products', models.IntegerField(default=0)),
                ('failed_products', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Log de Sincronização',
                'verbose_name_plural': 'Logs de Sincronização',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('next_sync', models.DateTimeField(blank=True, null=True)),
                ('sync_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='affiliates.platform')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syncs', to='products.product')),
            ],
            options={
                'verbose_name': 'Sincronização de Produto',
                'verbose_name_plural': 'Sincronizações de Produtos',
                'ordering': ['-last_synced'],
            },
        ),
    ]
