# Generated by Django 6.1 on 2026-08-27 00:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Descrição única para a página da categoria')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/%Y/%m/')),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('canonical_url', models.URLField(blank=True, help_text='URL canônica se diferente da atual')),
                ('noindex', models.BooleanField(default=False, help_text='Marque para não indexar')),
                ('nofollow', models.BooleanField(default=False, help_text='Marque para não seguir links')),
                ('order', models.PositiveIntegerField(default=0, help_text='Ordem de exibição')),
                ('is_active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False, help_text='Exibir na página inicial')),
                ('schema_type', models.CharField(choices=[('CollectionPage', 'Collection Page'), ('ItemList', 'Item List'), ('FAQPage', 'FAQ Page')], default='CollectionPage', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='products.category', verbose_name='Categoria Pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('short_description', models.CharField(blank=True, help_text='Descrição curta para cards e meta description', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Conteúdo ORIGINAL - mínimo 300 palavras para SEO')),
                ('main_image', models.URLField(blank=True, max_length=500)),
                ('image_alt', models.CharField(blank=True, help_text='Alt text para SEO', max_length=200)),
                ('gallery', models.JSONField(blank=True, default=list, help_text='Lista de URLs de imagens')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo'), ('out_of_stock', 'Esgotado'), ('discontinued', 'Descontinuado'), ('price_drop', 'Queda de Preço')], db_index=True, default='active', max_length=20)),
                ('featured', models.BooleanField(db_index=True, default=False, help_text='Sincroniza preço a cada 1h')),
                ('is_bestseller', models.BooleanField(default=False, help_text='Marcar como mais vendido')),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('price_updated_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('5'))])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=70)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('keywords', models.CharField(blank=True, help_text='Separadas por vírgula', max_length=255)),
                ('canonical_url', models.URLField(blank=True)),
                ('noindex', models.BooleanField(default=False)),
                ('nofollow', models.BooleanField(default=False)),
                ('schema_type', models.CharField(choices=[('Product', 'Product'), ('ProductGroup', 'Product Group')], default='Product', max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('sku', models.CharField(blank=True, max_length=100, unique=True)),
                ('gtin', models.CharField(blank=True, help_text='EAN/UPC para schema.org', max_length=14)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Taxa de conversão em %', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='Categoria')),
                ('related_products', models.ManyToManyField(blank=True, help_text='Produtos relacionados manualmente', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug', 'is_active'], name='products_ca_slug_269ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent', 'order'], name='products_ca_parent__978bbd_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['slug', 'status'], name='products_pr_slug_a31a62_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status', '-created_at'], name='products_pr_categor_23d7e7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['featured', 'status'], name='products_pr_feature_20d464_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['current_price', 'status'], name='products_pr_current_2aebe8_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['view_count'], name='products_pr_view_co_64c090_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-updated_at'], name='products_pr_updated_30df3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('current_price__isnull', True), ('current_price__gte', 0), _connector='OR'), name='current_price_non_negative'),
        ),
    ]
